{{ if eq .Values.db.deployment "operator" }}
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: fruits
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: fruits
  service:
    apiVersion: postgres-operator.crunchydata.com/v1beta1
    kind: PostgresCluster
    name: hippo
{{ end }}
