apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  annotations:
    # This object has to be created after completion of the Shipwright build
    # that creates the Helm repository image and after successful deployment
    # of this image.
    argocd.argoproj.io/sync-wave: "40"
  name: fruits-charts
spec:
  name: fruits-charts
  connectionConfig:
    url: http://helm-repository.fruits-dev.svc:8080
